// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const isInvalidDatabaseUrl = (value: string | undefined) => {
  const trimmed = value?.trim()
  if (!trimmed) return true
  if (trimmed === "undefined" || trimmed === "null") return true
  if (trimmed.includes("your-db-name") || trimmed.includes("your-auth-token")) return true
  return false
}

const databaseUrl =
  (!isInvalidDatabaseUrl(process.env.DATABASE_URL)
    ? process.env.DATABASE_URL!.trim()
    : !isInvalidDatabaseUrl(process.env.TURSO_DATABASE_URL)
      ? process.env.TURSO_DATABASE_URL!.trim()
      : undefined) ?? "file:./dev.db"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
